<#
Simple installer script for SOFME (PowerShell).
Usage: Run as Administrator on the target notebook.
This script copies the contents of the bundled folder (dist\SOFME) into
`C:\Program Files\SOFME`, creates Start Menu and Desktop shortcuts, and
adds an uninstall script.
#>

param(
    [string]$SourceFolder = "$PSScriptRoot\..\dist\SOFME",
    [string]$TargetFolder = "C:\Program Files\SOFME",
    [switch]$CreateDesktopShortcut = $true
)

function Require-Admin {
    $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Write-Error "Este instalador precisa ser executado como Administrador. Clique com o botão direito e escolha 'Executar como administrador'."
        exit 1
    }
}

function Copy-Files {
    param($src, $dst)
    if (-not (Test-Path $src)) { Write-Error "Pasta de origem não encontrada: $src"; exit 1 }
    if (-not (Test-Path $dst)) { New-Item -ItemType Directory -Path $dst -Force | Out-Null }
    Write-Host "Copiando arquivos de $src para $dst..."
    Copy-Item -Path (Join-Path $src '*') -Destination $dst -Recurse -Force
}

function New-Shortcut {
    param($targetPath, $shortcutPath, $args='')
    $shell = New-Object -ComObject WScript.Shell
    $shortcut = $shell.CreateShortcut($shortcutPath)
    $shortcut.TargetPath = $targetPath
    if ($args) { $shortcut.Arguments = $args }
    $shortcut.WorkingDirectory = Split-Path $targetPath
    $shortcut.Save()
}

Require-Admin

$src = Resolve-Path $SourceFolder -ErrorAction SilentlyContinue
if (-not $src) { Write-Error "Pasta de build não encontrada: $SourceFolder. Gere o build e coloque em dist\\SOFME."; exit 1 }
$src = $src.Path

Copy-Files -src $src -dst $TargetFolder

# Create Start Menu shortcut
$startMenu = Join-Path $env:ProgramData "Microsoft\Windows\Start Menu\Programs\SOFME"
if (-not (Test-Path $startMenu)) { New-Item -ItemType Directory -Path $startMenu -Force | Out-Null }
$exePath = Join-Path $TargetFolder 'SOFME.exe'
if (-not (Test-Path $exePath)) {
    # try to find exe inside target folder
    $exe = Get-ChildItem -Path $TargetFolder -Filter *.exe -Recurse | Select-Object -First 1
    if ($exe) { $exePath = $exe.FullName } else { Write-Warning "Não encontrei executável em $TargetFolder" }
}
$shortcutPath = Join-Path $startMenu 'SOFME.lnk'
New-Shortcut -targetPath $exePath -shortcutPath $shortcutPath

if ($CreateDesktopShortcut) {
    $desktop = [Environment]::GetFolderPath('Desktop')
    $desktopShortcut = Join-Path $desktop 'SOFME.lnk'
    New-Shortcut -targetPath $exePath -shortcutPath $desktopShortcut
}

# Create an uninstall script
$uninstall = Join-Path $TargetFolder 'uninstall.ps1'
@"
`# Uninstall script generated by installer
param()
Write-Host 'Removendo atalho do Menu Iniciar e desktop...'
Remove-Item -Path '$shortcutPath' -ErrorAction SilentlyContinue
Remove-Item -Path '$desktopShortcut' -ErrorAction SilentlyContinue
Write-Host 'Removendo pasta de instalação...'
Start-Sleep -Seconds 1
Remove-Item -LiteralPath '$TargetFolder' -Recurse -Force -ErrorAction SilentlyContinue
Write-Host 'Desinstalação concluída.'
"@ | Out-File -FilePath $uninstall -Encoding UTF8

Write-Host "Instalação concluída. Atalho criado em: $shortcutPath" -ForegroundColor Green
